apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-xxx-plugin-component
  annotations:
    backstage.io/managed-by-location: url:https://github.com/zepouet/backstage/blob/main/catalog-info.yaml
spec:
  lifecycle: production
  owner: my-team
  type: service
